package com.model;
// Generated 01-Dec-2019 15:18:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Election generated by hbm2java
 */
@Entity
@Table(name="election"
    ,catalog="evoting"
)
public class Election  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int year;

    public Election() {
    }

    public Election(String name, int year) {
       this.name = name;
       this.year = year;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }

    @Override
    public String toString() {
        return "Election{" + "id=" + id + ", name=" + name + ", year=" + year + '}';
    }




}


