package com.model;
// Generated 01-Dec-2019 15:18:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Party generated by hbm2java
 */
@Entity
@Table(name="party"
    ,catalog="evoting"
)
public class Party  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set candidates = new HashSet(0);

    public Party() {
    }

	
    public Party(String name) {
        this.name = name;
    }
    public Party(String name, Set candidates) {
       this.name = name;
       this.candidates = candidates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="party")
    public Set getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Set candidates) {
        this.candidates = candidates;
    }

    @Override
    public String toString() {
        return "Party{" + "id=" + id + ", name=" + name + ", candidates=" + candidates + '}';
    }




}


