package com.model;
// Generated 01-Dec-2019 15:18:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vote generated by hbm2java
 */
@Entity
@Table(name="vote"
    ,catalog="evoting"
)
public class Vote  implements java.io.Serializable {


     private Integer id;
     private int electionId;
     private int candidateId;
     private Date dateofvote;

    public Vote() {
    }

    public Vote(int electionId, int candidateId, Date dateofvote) {
       this.electionId = electionId;
       this.candidateId = candidateId;
       this.dateofvote = dateofvote;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="election_id", nullable=false)
    public int getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(int electionId) {
        this.electionId = electionId;
    }

    
    @Column(name="candidate_id", nullable=false)
    public int getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(int candidateId) {
        this.candidateId = candidateId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateofvote", nullable=false, length=19)
    public Date getDateofvote() {
        return this.dateofvote;
    }
    
    public void setDateofvote(Date dateofvote) {
        this.dateofvote = dateofvote;
    }

    @Override
    public String toString() {
        return "Vote{" + "id=" + id + ", electionId=" + electionId + ", candidateId=" + candidateId + ", dateofvote=" + dateofvote + '}';
    }




}


