package com.model;
// Generated 01-Dec-2019 15:18:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Voterelection generated by hbm2java
 */
@Entity
@Table(name="voterelection"
    ,catalog="evoting"
)
public class Voterelection  implements java.io.Serializable {


     private Integer id;
     private int voterId;
     private int electionId;

    public Voterelection() {
    }

    public Voterelection(int voterId, int electionId) {
       this.voterId = voterId;
       this.electionId = electionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="voter_id", nullable=false)
    public int getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(int voterId) {
        this.voterId = voterId;
    }

    
    @Column(name="election_id", nullable=false)
    public int getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(int electionId) {
        this.electionId = electionId;
    }




}


